version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: scheduler
    ports:
      - '5432:5432'
  api:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
